apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-job
spec:
  jobTemplate:
    metadata:
      name: my-job
    spec:
      template:
        spec:
          containers:
          - command:
            - date
            image: busybox:1.37
            name: my-job
            resources: {}
          restartPolicy: OnFailure
  schedule: '*/2 * * * *'