# .commitlintrc.yml
extends:
  - "@commitlint/config-conventional"

rules:
  type-enum:
    - 2
    - always
    - [feat, fix, hotfix, release, refactor, perf, style, test, docs, chore, ci, build, revert]

  scope-case:
    - 2
    - always
    - lower-case

  subject-case:
    - 2
    - always
    - sentence-case

  subject-empty:
    - 2
    - never

  subject-max-length:
    - 2
    - always
    - 72

  body-max-line-length:
    - 2
    - always
    - 250

  footer-max-line-length:
    - 2
    - always
    - 250
