title: "🛸 schwifty-lab | Hiro’s Blog"
tagline: "Exploring Kubernetes, DevOps, and the Future of Cloud-Native Technology"
description: "Practical guides, tips, and insights on Kubernetes, microservices, and DevOps, from beginner-friendly tutorials to expert strategies."
show_downloads: false

nav:
  - title: "Home"
    url: /
  - title: "Articles"
    url: /articles/
  - title: "About Me"
    url: /about-me/

theme: blog-jekyll-theme

exclude:
- projects