apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: blogcategories.blog.supaahiro.io
spec:
  group: blog.supaahiro.io
  names:
    plural: blogcategories
    singular: blogcategory
    kind: BlogCategory
    shortNames:
      - bc
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - id
                - displayName
              properties:
                id:
                  type: string
                  description: "Unique identifier of the category."
                displayName:
                  type: string
                  description: "Title of the category."
