apiVersion: v1
kind: ResourceQuota
metadata:
  name: team-budget
  namespace: ckad-resource-policy
spec:
  hard:
    requests.cpu: 500m
    requests.memory: 512Mi
    limits.cpu: "1"
    limits.memory: 1Gi
    pods: "4"
