apiVersion: v1
kind: LimitRange
metadata:
  name: container-bounds
  namespace: ckad-resource-policy
spec:
  limits:
    - type: Container
      min:
        cpu: 50m
        memory: 16Mi
      max:
        cpu: 500m
        memory: 256Mi
      defaultRequest:
        cpu: 100m
        memory: 64Mi
      default:
        cpu: 250m
        memory: 128Mi
