apiVersion: v1
kind: Pod
metadata:
  name: config-args
  namespace: ckad-configmaps
spec:
  restartPolicy: Never
  automountServiceAccountToken: false
  containers:
    - name: printer
      image: busybox:1.37.0
      command: ["/bin/echo"]
      args: ["Mode=$(APP_MODE)"]
      env:
        - name: APP_MODE
          valueFrom:
            configMapKeyRef:
              name: app-settings
              key: APP_MODE
