apiVersion: blog.supaahiro.io/v1alpha1
kind: BlogPost
metadata:
  name: 20251020-ckad-build-a-container-image
spec:
  id: 20251020-ckad-build-a-container-image
  title: "CKAD Preparation \u2014 Build a container image"
  previewImage: https://supaahiro.github.io/schwifty-lab/blog-posts/20251020-ckad/article.webp
  summary: Learn how to turn a Python/FastAPI service into a fully containerized app,
    run it locally with Docker, and seamlessly deploy it to Kubernetes.
  contentUrl: https://raw.githubusercontent.com/SupaaHiro/schwifty-lab/refs/heads/master/blog-posts/20251020-ckad/article_EN.md
  publishedOn: '2025-10-20T00:00:00Z'
  author: Hiro
  categoryId: ckad-preparation
  relatedPostsIds: []
status:
  published: true
